### ISSUE TITLE
WebID a system, vs WebID an HTTP URI that ...

### ISSUE THREAD

**Issue by melvincarvalho** [w3c/WebID#40]
Revisit the terminology section to ensure clear distinction between 'WebID' as an identifier and the broader identity system in: https://github.com/jacoscaz/WebID/blob/main/primary-spec/webid.html

In particular the abstract could be clearer in what "WebID" is and what "a WebID"

The term has multiple uses of course, an ecosystem, a suite of specifications, an HTTP URI etc.

The abstract was quickly put together and we can certainly improve it and clarify terms, as requested in https://github.com/w3c/WebID/issues/37#issuecomment-1879784012

**Comment by melvincarvalho** [comment]
Current Abstract:

> WebID defines a standard means by which user agents and servers interact to establish a user's identity, ensuring a structured, decentralized approach for identity discovery on the web.

How about:

> **The WebID set of standards**, define a means by which **clients** and servers interact to establish a user's identity, ensuring a structured, **loosely-coupled**,  approach to identity and discovery on the web.

@kidehen is this better?  Any suggestions?

**Comment by jacoscaz** [comment]
_/chair hat on_

Just to keep everyone aligned, the abstract in [my draft](https://jacoscaz.com/WebID/primary-spec/webid.html) now goes as follows:

> This specification defines a standard means by which user agents and servers interact to establish a user's identity, ensuring a structured, decentralized approach for identity discovery on the web.

Also, and I'll probably repeat this many times but it bears repeating for clarity, remember that my draft is not meant to replace the 2014 ED, at least for now. It merely aims to provide an integrated view of where the group stands - a representation of consensus, if you will.

_/chair hat off_

That said, I find that the solution proposed by @melvincarvalho further clarifies things, so +1 from me on it. Quoted below for reference:

> The WebID set of standards, define a means by which clients and servers interact to establish a user's identity, ensuring a structured, loosely-coupled, approach to identity and discovery on the web.

**Comment by kidehen** [comment]
> **The WebID set of standards**, define a means by which **clients** and servers interact to establish a user's identity, ensuring a structured, **loosely-coupled**, approach to identity and discovery on the web.

No it doesn't. 
I proposed leveraging the recursive acronym that's already in the [existing spec](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/identity-respec.html) to reduce friction. Basically, the term "WebID" comprises two things:

1. An identifier
1. An identification system


Remember, a "Name" comprises two things too:

1. Denotatation
2. Connotation 

My goal is to use the existing spec to make the above clearer. Once that's achieved, we can then move on to loosening Turtle dependency.

**Comment by kidehen** [comment]
> This specification defines a standard means by which user agents and servers interact to establish a user's identity, ensuring a structured, decentralized approach for identity discovery on the web.

I can live with that, but I would suggest the following variation:

This specification defines a standard means by which an _agent_ is named _unambiguously_. It addresses _user agents_ and _servers_ interactions for establishing _agent identity_, leveraging [the same architecture](https://www.w3.org/TR/webarch/) that  underlies the World Wide Web.

**Comment by jacoscaz** [comment]
_/chair hat off_

Ok, let's see:

Option 1., currently in my draft:

> This specification defines a standard means by which user agents and servers interact to establish a user's identity, ensuring a structured, decentralized approach for identity discovery on the web.

Option 2., suggested by @melvincarvalho 

> The WebID set of standards, define a means by which clients and servers interact to establish a user's identity, ensuring a structured, loosely-coupled, approach to identity and discovery on the web.

Option 3., suggested by @kidehen 

> This specification defines a standard means by which an agent is named unambiguously. It addresses user agents and servers interactions for establishing agent identity, leveraging [the same architecture](https://www.w3.org/TR/webarch/) that underlies the World Wide Web.

I do not consider any of these a blocker, though I do have a slight preference towards Option 1. not because it's the one already in my draft but because I subjectively find it clearer and easier to understand. Separately, it might be the one that most of us _could live with_.

Usual disclaimer: this is note a formal call for voting. I'm just trying to facilitate stating one's preferences.

**Comment by jacoscaz** [comment]
Closed by #60.
