### ISSUE TITLE
Web Discovery?

### ISSUE THREAD

**Issue by TallTed** [w3c/WebID#54]
The 2014 ED has 2 instances of "discovery" (and none of "discover") — and one is in the subtitle.

The other is in context of Content Negotiation — i.e., it's just about `discovery of multiple distinct serializations of the same graph at the same URL`

```html
WebID requires that servers <em class="rfc2119" title="MUST">MUST</em> at least be able
to provide Turtle representation of profile documents, but other serialization formats
of the graph are allowed, provided that agents are able to parse that serialization and
obtain the graph automatically.

HTTP Content Negotiation can be employed to aid in publication and discovery of multiple
distinct serializations of the same graph at the same URL, as explained in
[<cite><a class="bibref" href="#bib-COOLURIS">COOLURIS</a></cite>]</p>
```

If we're going to keep the subtitle (or now, title!) of `Web Identity and Discovery (WebID)`, I think we need some significant discussion of how `WebID` delivers `Discovery` of more than alternate RDF serializations.

**Comment by TallTed** [comment]
I'm in favor of dropping `Discovery`.

In my mind, `WebID` uses `ID` in a way any database or driver's license user is familiar with, and just drops a space and changes `{IDentifier|IDentification|IDentity}` to `ID` — i.e., it mentally expands to `Web IDentifier`, `Web IDentification`, and/or `Web IDentity` (depending on the *specific* context of its appearance, as I hope we can all agree there are significant differences between these three expansions of `ID`).

**Comment by jacoscaz** [comment]
_/chair hat on_

To all: as much as we can, let's try to keep things separate. This issue is about the word `Discovery`. Dropping it from the title we settled on in #37 would lead to `Web Identity (WebID)`, which _insofar as I can tell_ has an element of recursion in it. 

_Personally_ I'm still not grokking the recursion argument but @kidehen and others have been making the case for it for a long time with no objections to their arguments. We can re-evaluate having a recursive-ish title, of course, but let's do so in a different issue if needed at all.

**Comment by kidehen** [comment]
"Discovery" deals with the "reference" and "lookup" aspects of a WebID i.e., its resolution to a profile document. That's why it exists in the [current spec](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/identity-respec.html). 

It shouldn't be altered, since that will ultimately taint the progress made so far -- IMHO.

**Comment by TallTed** [comment]
> A WebID provides a starting point for follow-your-nose exploration of a variety of things associated with a WebID's referent.

OK... Then *at a minimum*, I would expect an example of such to be found in the text of the document. I find no such in the latest 2014 ED. The closest I found in the Mercurial dump of that document's history was in a (long since excised) section connecting WebID to OpenID, which removal appears to have been appropriate given that neither WebID nor OpenID depends on the other in any ongoing way.

**Comment by jacoscaz** [comment]
_/chair hat off_

> A WebID provides a starting point for follow-your-nose exploration of a variety of things associated with a WebID's referent.

Good point. I think it'd be enough to add this in the abstract to clarify the role of the word _Discovery_.

**Comment by melvincarvalho** [comment]
I dont understand the importance of the "recursive" part, nor do I know anyone that likes the "recursive" part.  That could be better explained.

@deiu introduced the term 'discovery' in 2013, which I think just meant using linked data to discover things.

**Comment by kidehen** [comment]
Yes, and it packs follow-your-nose discovery into a single word.  Discovery is an important aspect of a WebID.

**Comment by melvincarvalho** [comment]
As we discussed back then, though, discovery is different from follow your nose.  For example, webfinger is discovery, but does not use follow your nose.

Much of this will be self-evident with examples.

I think framing it as entities, attributes and values using JSON will be much more intuitive to Web Developers, than emphasizing RDF and Turtle.  So, I prefer the term "machine readable" with reference to data, and then for the "discovery" aspect to become self-evident from worked examples.  Copy-paste, then change to suit deployment needs.  Seems the path to success.

**Comment by kidehen** [comment]
Follow-your-nose is just a TimBL-ism for dereferencing and graph structure constructed from pointers. That's process facilitates discovery. 

Programmers understand the concept of 'data access by reference' in relation to structured data representation. The key point here is that "Discovery" is a single word that associates all of this with an HTTP URI, in the context of a specification titled 'WebID and Discovery'  :)

Asking ChatGPT to put this all together and it produced a pretty useful response:
"_Programmers are familiar with the concept of 'data access by reference' in the realm of structured data representation. This concept is pivotal in understanding how data elements are interconnected and accessed in a structured manner. The essence of this concept is succinctly encapsulated in a single, powerful word: 'Discovery.' This term gains even more significance in the context of the 'WebID and Discovery' specification, where it's linked directly to HTTP URIs. Understanding 'Discovery' within this framework is key to grasping the full potential and functionality of the 'WebID and Discovery' specification. It's not just about locating resources; it's about establishing a more intuitive and interconnected web of data, accessible through standardized references._"

**Comment by melvincarvalho** [comment]
Yes, but discovery is not the same as follow your nose, though follow your nose is an aspect if discovery

Discovery is not the same as data access by reference, though data access by reference is an aspect of discovery

Discovery is about having machine readable data, and *through a process* discovering *more* machine readable data

**Comment by kidehen** [comment]
Put differently, a WebID opens up a world of discovery. This is a fact, due to the nature of an HTTP URI that resolves to an entity relationship graph comprising machine-readable entity relationship type semantics.

**Comment by melvincarvalho** [comment]
> I'd posit that the term Web in WebID, is in fact the single word that associates all of this with an HTTP URI.

That's a pretty powerful observation.  The term "web" is so overused, that it's become a cliche.  Yet actually delivering a a first class "Web" Identity system is what this group has always been about.   

Indeed, I would argue none exist today, that can be deployed at scale. We have a chance to fix that.

**Comment by kidehen** [comment]
> I'd posit that the term Web in WebID, is in fact the single word that associates all of this with an HTTP URI.

Not so simple. 
ID can stand for: 

1. Identity -- what an identifier enables
2. Identification -- what a profile doc enables

"Discovery" solves for the issue of 1 or 2,  which is how I believe the [original spec](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/identity-respec.html) ended up with "WebID Identity and Discovery" 

I really think we should leave this as is, there are bigger issues to handle e.g., sorting out JSON-LD support. That's the biggest material issue -- IMHO.

**Comment by kidehen** [comment]
> The original term discovery was introduced [here](https://lists.w3.org/Archives/Public/public-webid/2013Feb/0014.html) because it was essential to discover a nested key from from a WebID e.g. using complex tech such as SPARQL. Actually it can be traced back to 2012 if you follow the minutes, but then things get a bit lost.

Okay, and I don't see how anything you've stated above is incompatible with the variety of explanations I've provided about the meaning of "Discovery" in the original spec. 

There's something to "discover" when you resolve a WebID to an entity relationship graph comprising machine-readable entity relationship type semantics :)

**Comment by kidehen** [comment]
> I guess perhaps they can be seen as redundant and adding needless complexity.
> 
> Web = Web ID = ident*
> 
> It covers everything

I disagree, especially as we should be seeking to only make important (i.e., blocking) changes, unobtrusively, to the [current spec](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/identity-respec.html). Fundamentally, "Discovery" is already in use -- so I encourage leaving it as is. 

JSON-LD parity with Turtle is a much more important issue.

**Comment by jacoscaz** [comment]
_/chair hat on_

@TallTed is yours a strong objection to keeping "Discovery" or could you live with it? 

@kidehen is yours a strong objection to dropping "Discovery" or could you live with it?

Does anyone else have strong objections towards one or the other?

**Comment by melvincarvalho** [comment]
No objections, given Ted and Kingsley are at the same company, perhaps they could figure out between them what they want?

**Comment by TallTed** [comment]
I'm fine with keeping Discovery in the title *if* the body content gets some more detail about that element of "discovery". The single sentence now containing that word (and no sentences including the word "discover") is *not* sufficient, imho, especially given the number of sentences about "Identity".

Perhaps something could be added about how to "discover a nested key from from a WebID, e.g., using complex tech such as SPARQL" or using simpler tech such as a Turtle (or JSON-LD) parser?

**Comment by kidehen** [comment]
The body text can be enhanced to shed light on discovery scenarios facilitated by a WebID. We can even put that together, if necessary.

**Comment by melvincarvalho** [comment]
> I have a strong objection to keeping `Identity and Discovery`

+1 Discovery is not necessary in a micro spec, and has never been defined

Frome reading this thread, outside of Openlink, no one is pushing for this.

Suggest closing.

**Comment by jacoscaz** [comment]
_/chair hat on_

The current title of the working draft ([link rendered version](https://w3c.github.io/WebID/spec/identity/index.html)) is `Web Identity and Discovery`, though this is likely a mistake as #37 pointed towards `Web Identity and Discovery (WebID) 1.0`.

Summarizing the above and based on past conversations, I think we have the following alternatives to pick from:

1. `Web Identity and Discovery (WebID) 1.0` as-is
2. `Web Identity and Discovery (WebID) 1.0` with some more detail about the "discovery" element
3. `Web Identity (WebID) 1.0`

_/chair hat off_

No blockers on my end but soft preference for option 2. , with the following paragraph as the additional detail:

> A WebID provides a starting point for follow-your-nose exploration of a variety of things associated with a WebID's referent.
