### ISSUE TITLE
Profile vs Person

### ISSUE THREAD

**Issue by melvincarvalho** [w3c/WebID#59]
The new WebID definition is almost there.

The Profile Document I think is pretty much there.

A long standing question that I have is what is the difference between a Profile and a Person

When to use either?

Profile as in PersonalProfileDocument with primaryTopic for example

1. If a document is a profile document, why isnt the primary topic a Profile?  Maybe @danbri knows this.
2. Is there a @type for Profile as well as Person
3. Are there cases where Profile and Person could live in the same document

My working assumption is that Profile is not really used, and is a catch all term for Agent.  But I'd like to double check this assumption, before starting an implementation.

**Comment by namedgraph** [comment]
A person cannot be directly dereferenced over HTTP, the profile document can. This is [HTTPRange-14](https://en.wikipedia.org/wiki/HTTPRange-14).

**Comment by melvincarvalho** [comment]
Thanks.  So the primary topic of the profile document is indeed a person.  But its actually a PersonDocument, but that sounds a bit strange, so ProfileDocument is used.  So there is no actual "Profile" in the end, does that sound right?

**Comment by melvincarvalho** [comment]
Thanks for the feedback, closing.
